### ISSUE TITLE
Message parsing

### ISSUE THREAD

**Issue by hugeblank** [CSSDC/ChatApp#3]
The way you parse the raw message is highly inefficient and isn’t very modular. I plan on submitting a PR fixing this, and shipping a new feature.

**Comment by xseano** [comment]
Are you referring to how to format the data (https://github.com/CSSDC/ChatApp/blob/master/client/resources/js/utility.js#L32) and parse it (https://github.com/CSSDC/ChatApp/blob/master/server/user.js#L89-L90)? 

Or are you referring to how I package/parse the data with the Binary Reader/Writer library (https://github.com/CSSDC/libbinary)?

**Comment by xseano** [comment]
You're certainly right, delimiting the data by "%" is not comprehensive at all. It's easy to do it that way because then all data is in one string and it's easy to iterate through each character, assign its uint8 value, and move on.

The issue lies with the fact that we have to send three both the name and color in one packet. If you can think of a better solution, go ahead and implement then submit a PR for review.

**Comment by xseano** [comment]
To answer your question- If a user typed "te%st", it would break the current existential system.

**Comment by hugeblank** [comment]
Yeah that’s a problem. I’ll look into ways to fix it. The first thing that comes to mind is the utf-8 equivalent to a null character, or something that the user can’t type out.

**Comment by xseano** [comment]
That's a good idea, thanks.

**Comment by xseano** [comment]
Implementation @ aace29e064a319f91165dda0b9f4d15843d4375f.
